import Head from "next/head";

// ====================================================================

// ====================================================================

const SEO = ({ title, description="Santri Hub - Platform Seputar Kampus dan Beasiswa", sitename = "Home" }) => {
  return (
    <Head>
      <title>{`${title} | ${sitename}`}</title>
      <meta name="description" content={description} />
      <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.app.santrihub.or.id/template/assets/images/favicon-santrihub.png"
        />
        <link
          rel="shortcut icon"
          href="https://www.app.santrihub.or.id/template/assets/images/favicon-santrihub.png"
        />

        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="author" content="apps.santrihub.or.id" />
        <meta data-rh="true" property="og:site_name" content="Santri Hub" />
        <meta
          data-rh="true"
          property="og:title"
          content="Situs Seputar Kampus dan Beasiswa Terlengkap &amp; Terintegerasi | Santri Hub"
        />
        <meta
          data-rh="true"
          property="og:description"
          content="Situs seputar kampus dan beasiswa terlengkap dengan berbagai kategori"
        />
        <meta
          name="description"
          content="Santri Hub - Platform Seputar Kampus dan Beasiswa"
        />
        <meta
          data-rh="true"
          property="og:description"
          content="Situs seputar kampus dan beasiswa terlengkap dengan berbagai kategori"
        />
        <meta
          data-rh="true"
          name="description"
          content="Situs seputar kampus dan beasiswa terlengkap dengan berbagai kategori "
        />
    </Head>
  );
};
export default SEO;
